# app_gan.py
import streamlit as st
import os

GAN_DIR = (
    r"C:\Users\seife\OneDrive\Desktop\MAIM-Internship\Final_Project\generated_data"
)

st.title("♻️ GAN Image Augmentation")
st.write("Preview synthetic waste images generated by the GAN.")

if os.path.exists(GAN_DIR) and len(os.listdir(GAN_DIR)) > 0:
    cols = st.columns(4)
    for i, img_name in enumerate(os.listdir(GAN_DIR)[:8]):  # show first 8 samples
        img_path = os.path.join(GAN_DIR, img_name)
        with cols[i % 4]:
            st.image(img_path, use_column_width=True)
else:
    st.warning(
        "⚠️ No GAN samples found. Train GAN and save images in `generated_data/`."
    )
